import type { 
  User, 
  Property, 
  Payment, 
  Contract, 
  MaintenanceRequest, 
  Inquiry, 
  Equipment, 
  Vehicle 
} from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'user-customer-1',
    email: 'hans@tesrealestate.com',
    password: 'customer123',
    name: 'Hans Lagmay',
    phone: '+63 917 123 4567',
    role: 'customer',
    status: 'active',
    createdAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'user-agent-1',
    email: 'juan@tesrealestate.com',
    password: 'agent123',
    name: 'Juan Dela Cruz',
    phone: '+63 917 234 5678',
    role: 'agent',
    status: 'active',
    licenseNumber: 'PRC-12345',
    agency: 'TES Real Estate',
    createdAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: 'user-admin-1',
    email: 'admin@tesrealestate.com',
    password: 'admin123',
    name: 'Admin User',
    phone: '+63 917 345 6789',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-01-01').toISOString(),
  },
];

export const DEMO_PROPERTIES: Property[] = [
  {
    id: 'prop-1',
    agentId: 'user-agent-1',
    title: 'Modern Downtown Condo',
    type: 'Condo',
    price: 12000000,
    location: 'Manila',
    bedrooms: 2,
    bathrooms: 2,
    area: 65,
    description: 'Stunning modern condo in the heart of Manila with city views. Features high-quality finishes, modern appliances, and access to world-class amenities including a pool, gym, and business center.',
    photos: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    status: 'active',
    views: 125,
    createdAt: new Date('2024-09-15').toISOString(),
    updatedAt: new Date('2024-09-15').toISOString(),
  },
  {
    id: 'prop-2',
    agentId: 'user-agent-1',
    title: 'Luxury Beach House',
    type: 'House',
    price: 35000000,
    location: 'Boracay',
    bedrooms: 4,
    bathrooms: 3,
    area: 250,
    description: 'Exclusive beachfront property with direct beach access. Perfect for families seeking a tropical paradise with modern comforts. Features expansive living spaces, infinity pool, and breathtaking ocean views.',
    photos: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    ],
    status: 'active',
    views: 287,
    createdAt: new Date('2024-08-20').toISOString(),
    updatedAt: new Date('2024-08-20').toISOString(),
  },
  {
    id: 'prop-3',
    agentId: 'user-agent-1',
    title: 'Cozy Studio Apartment',
    type: 'Apartment',
    price: 6000000,
    location: 'Makati',
    bedrooms: 0,
    bathrooms: 1,
    area: 28,
    description: 'Perfect starter home or investment property in the business district. Fully furnished with modern amenities, walking distance to offices, restaurants, and entertainment. Ideal for young professionals.',
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800',
    ],
    status: 'active',
    views: 198,
    createdAt: new Date('2024-10-01').toISOString(),
    updatedAt: new Date('2024-10-01').toISOString(),
  },
  {
    id: 'prop-4',
    agentId: 'user-agent-1',
    title: 'Family Home with Garden',
    type: 'House',
    price: 18000000,
    location: 'Quezon City',
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    description: 'Spacious family home with a beautiful garden and garage. Located in a quiet residential area with excellent schools nearby. Features spacious living areas, modern kitchen, and ample storage.',
    photos: [
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
      'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    status: 'active',
    views: 156,
    createdAt: new Date('2024-09-10').toISOString(),
    updatedAt: new Date('2024-09-10').toISOString(),
  },
  {
    id: 'prop-5',
    agentId: 'user-agent-1',
    title: 'Penthouse with City View',
    type: 'Condo',
    price: 45000000,
    location: 'BGC',
    bedrooms: 3,
    bathrooms: 3,
    area: 200,
    description: 'Ultra-luxurious penthouse with 360-degree city views. Features premium finishes, smart home technology, private elevator access, and a spacious terrace perfect for entertaining.',
    photos: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
      'https://images.unsplash.com/photo-1600607687644-c7171b42498b?w=800',
    ],
    status: 'active',
    views: 342,
    createdAt: new Date('2024-07-15').toISOString(),
    updatedAt: new Date('2024-07-15').toISOString(),
  },
  {
    id: 'prop-6',
    agentId: 'user-agent-1',
    title: 'Suburban Townhouse',
    type: 'House',
    price: 15000000,
    location: 'Alabang',
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    description: 'Modern townhouse in a secure subdivision. Great for starting families with clubhouse amenities, parks, and 24/7 security. Close to shopping centers and major highways.',
    photos: [
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?w=800',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=800',
    ],
    status: 'active',
    views: 223,
    createdAt: new Date('2024-09-25').toISOString(),
    updatedAt: new Date('2024-09-25').toISOString(),
  },
];

export const TIME_SLOTS = [
  '9:00 AM',
  '10:00 AM',
  '11:00 AM',
  '12:00 PM',
  '1:00 PM',
  '2:00 PM',
  '3:00 PM',
  '4:00 PM',
  '5:00 PM',
];

export const PROPERTY_TYPES = ['House', 'Condo', 'Apartment', 'Lot'];

export const LOCATIONS = ['Manila', 'Quezon City', 'Makati', 'BGC', 'Alabang', 'Boracay', 'Cebu', 'Davao'];

export const DEMO_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    appointmentId: 'appt-1',
    customerId: 'user-customer-1',
    propertyId: 'prop-1',
    agentId: 'user-agent-1',
    amount: 500000,
    status: 'paid',
    paymentDate: new Date('2024-10-15').toISOString(),
    dueDate: new Date('2024-10-10').toISOString(),
    receiptNumber: 'RCP-2025-000001',
    paymentMethod: 'bank_transfer',
    notes: 'Initial deposit for condo unit',
    createdAt: new Date('2024-10-05').toISOString(),
  },
  {
    id: 'pay-2',
    appointmentId: 'appt-2',
    customerId: 'user-customer-1',
    propertyId: 'prop-2',
    agentId: 'user-agent-1',
    amount: 1000000,
    status: 'pending',
    dueDate: new Date('2025-01-15').toISOString(),
    receiptNumber: 'RCP-2025-000002',
    notes: 'Second payment installment',
    createdAt: new Date('2024-11-01').toISOString(),
  },
  {
    id: 'pay-3',
    appointmentId: 'appt-3',
    customerId: 'user-customer-1',
    propertyId: 'prop-3',
    agentId: 'user-agent-1',
    amount: 300000,
    status: 'overdue',
    dueDate: new Date('2024-10-20').toISOString(),
    receiptNumber: 'RCP-2025-000003',
    notes: 'Monthly rental payment',
    createdAt: new Date('2024-10-01').toISOString(),
  },
];

export const DEMO_CONTRACTS: Contract[] = [
  {
    id: 'contract-1',
    appointmentId: 'appt-1',
    customerId: 'user-customer-1',
    propertyId: 'prop-1',
    agentId: 'user-agent-1',
    contractNumber: 'CNT-2025-000001',
    startDate: new Date('2024-11-01').toISOString(),
    endDate: new Date('2025-10-31').toISOString(),
    terms: 'Standard rental agreement for 1 year. Monthly payment of ₱50,000. Security deposit: ₱150,000. Utilities not included.',
    status: 'active',
    signedDate: new Date('2024-10-20').toISOString(),
    documentUrl: '#',
    createdAt: new Date('2024-10-15').toISOString(),
  },
  {
    id: 'contract-2',
    appointmentId: 'appt-2',
    customerId: 'user-customer-1',
    propertyId: 'prop-2',
    agentId: 'user-agent-1',
    contractNumber: 'CNT-2025-000002',
    startDate: new Date('2025-01-01').toISOString(),
    endDate: new Date('2025-12-31').toISOString(),
    terms: 'Vacation home rental agreement. Monthly payment of ₱100,000. 2 months advance, 2 months deposit. Property maintenance included.',
    status: 'active',
    signedDate: new Date('2024-11-05').toISOString(),
    documentUrl: '#',
    createdAt: new Date('2024-11-01').toISOString(),
  },
];

export const DEMO_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: 'maint-1',
    propertyId: 'prop-1',
    customerId: 'user-customer-1',
    agentId: 'user-agent-1',
    title: 'Leaking faucet in kitchen',
    description: 'The kitchen faucet has been leaking for the past 2 days. Water is dripping constantly even when turned off.',
    priority: 'medium',
    status: 'in_progress',
    category: 'plumbing',
    estimatedCost: 5000,
    contractorName: 'ABC Plumbing Services',
    scheduledDate: new Date('2024-11-12').toISOString(),
    notes: 'Contractor confirmed availability',
    createdAt: new Date('2024-11-08').toISOString(),
    updatedAt: new Date('2024-11-09').toISOString(),
  },
  {
    id: 'maint-2',
    propertyId: 'prop-2',
    customerId: 'user-customer-1',
    agentId: 'user-agent-1',
    title: 'Air conditioning not cooling',
    description: 'Master bedroom AC unit not cooling properly. Temperature is not dropping despite being set to lowest setting.',
    priority: 'high',
    status: 'pending',
    category: 'hvac',
    estimatedCost: 8000,
    notes: 'Urgent - summer season',
    createdAt: new Date('2024-11-09').toISOString(),
    updatedAt: new Date('2024-11-09').toISOString(),
  },
  {
    id: 'maint-3',
    propertyId: 'prop-1',
    customerId: 'user-customer-1',
    agentId: 'user-agent-1',
    title: 'Broken electrical outlet',
    description: 'Living room electrical outlet stopped working. Need electrician to check.',
    priority: 'urgent',
    status: 'completed',
    category: 'electrical',
    estimatedCost: 3000,
    actualCost: 2500,
    contractorName: 'XYZ Electrical',
    scheduledDate: new Date('2024-11-05').toISOString(),
    completedDate: new Date('2024-11-06').toISOString(),
    notes: 'Fixed and tested. Issue was faulty wiring.',
    createdAt: new Date('2024-11-04').toISOString(),
    updatedAt: new Date('2024-11-06').toISOString(),
  },
];

export const DEMO_INQUIRIES: Inquiry[] = [
  {
    id: 'inq-1',
    ticketNumber: 'TKT-2025-000001',
    customerId: 'user-customer-1',
    propertyId: 'prop-1',
    agentId: 'user-agent-1',
    subject: 'Question about parking availability',
    description: 'Hi, I would like to know if the condo unit comes with a parking slot. Also, is visitor parking available?',
    category: 'property',
    priority: 'medium',
    status: 'resolved',
    assignedTo: 'user-agent-1',
    responses: [
      {
        id: 'resp-1',
        inquiryId: 'inq-1',
        userId: 'user-agent-1',
        userRole: 'agent',
        message: 'Hello! Yes, the unit comes with 1 dedicated parking slot. Visitor parking is available on a first-come, first-served basis.',
        createdAt: new Date('2024-11-08T10:30:00').toISOString(),
      },
      {
        id: 'resp-2',
        inquiryId: 'inq-1',
        userId: 'user-customer-1',
        userRole: 'customer',
        message: 'Thank you for the information!',
        createdAt: new Date('2024-11-08T11:00:00').toISOString(),
      },
    ],
    createdAt: new Date('2024-11-08T09:00:00').toISOString(),
    updatedAt: new Date('2024-11-08T11:00:00').toISOString(),
  },
  {
    id: 'inq-2',
    ticketNumber: 'TKT-2025-000002',
    customerId: 'user-customer-1',
    subject: 'Payment confirmation not received',
    description: 'I made a payment 3 days ago via bank transfer but have not received any confirmation email. Can you please check?',
    category: 'payment',
    priority: 'high',
    status: 'in_progress',
    assignedTo: 'user-admin-1',
    responses: [
      {
        id: 'resp-3',
        inquiryId: 'inq-2',
        userId: 'user-admin-1',
        userRole: 'admin',
        message: 'We are checking with our finance team. Please provide your transaction reference number.',
        createdAt: new Date('2024-11-09T14:00:00').toISOString(),
      },
    ],
    createdAt: new Date('2024-11-09T09:00:00').toISOString(),
    updatedAt: new Date('2024-11-09T14:00:00').toISOString(),
  },
  {
    id: 'inq-3',
    ticketNumber: 'TKT-2025-000003',
    customerId: 'user-customer-1',
    subject: 'Website login issue',
    description: 'I am having trouble logging in to the website. The page keeps loading but never completes.',
    category: 'technical',
    priority: 'low',
    status: 'open',
    responses: [],
    createdAt: new Date('2024-11-10T08:00:00').toISOString(),
    updatedAt: new Date('2024-11-10T08:00:00').toISOString(),
  },
];

export const DEMO_EQUIPMENT: Equipment[] = [
  {
    id: 'eq-1',
    name: 'MacBook Pro 16"',
    type: 'laptop',
    serialNumber: 'MBP-2023-001',
    status: 'assigned',
    assignedTo: 'user-agent-1',
    assignedDate: new Date('2024-01-15').toISOString(),
    purchaseDate: new Date('2023-12-01').toISOString(),
    lastMaintenanceDate: new Date('2024-06-15').toISOString(),
    nextMaintenanceDate: new Date('2025-06-15').toISOString(),
    condition: 'excellent',
    notes: 'Primary work laptop for agent',
    createdAt: new Date('2023-12-01').toISOString(),
    updatedAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: 'eq-2',
    name: 'iPhone 15 Pro',
    type: 'phone',
    serialNumber: 'IPH-2024-001',
    status: 'assigned',
    assignedTo: 'user-agent-1',
    assignedDate: new Date('2024-02-01').toISOString(),
    purchaseDate: new Date('2024-01-15').toISOString(),
    condition: 'excellent',
    notes: 'Company phone for agent communications',
    createdAt: new Date('2024-01-15').toISOString(),
    updatedAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: 'eq-3',
    name: 'Canon EOS R5',
    type: 'camera',
    serialNumber: 'CAM-2023-001',
    status: 'available',
    purchaseDate: new Date('2023-08-01').toISOString(),
    lastMaintenanceDate: new Date('2024-08-01').toISOString(),
    nextMaintenanceDate: new Date('2025-08-01').toISOString(),
    condition: 'good',
    notes: 'Professional camera for property photography',
    createdAt: new Date('2023-08-01').toISOString(),
    updatedAt: new Date('2024-08-01').toISOString(),
  },
  {
    id: 'eq-4',
    name: 'iPad Air',
    type: 'tablet',
    serialNumber: 'IPD-2024-001',
    status: 'maintenance',
    purchaseDate: new Date('2024-03-01').toISOString(),
    lastMaintenanceDate: new Date('2024-11-01').toISOString(),
    nextMaintenanceDate: new Date('2024-11-15').toISOString(),
    condition: 'fair',
    notes: 'Screen replacement needed',
    createdAt: new Date('2024-03-01').toISOString(),
    updatedAt: new Date('2024-11-01').toISOString(),
  },
  {
    id: 'eq-5',
    name: 'Samsung Galaxy S24',
    type: 'phone',
    serialNumber: 'SAM-2024-001',
    status: 'available',
    purchaseDate: new Date('2024-04-01').toISOString(),
    condition: 'excellent',
    notes: 'Backup phone',
    createdAt: new Date('2024-04-01').toISOString(),
    updatedAt: new Date('2024-04-01').toISOString(),
  },
  {
    id: 'eq-6',
    name: 'Dell Laptop',
    type: 'laptop',
    serialNumber: 'DEL-2022-001',
    status: 'retired',
    purchaseDate: new Date('2022-01-01').toISOString(),
    lastMaintenanceDate: new Date('2024-01-01').toISOString(),
    condition: 'poor',
    notes: 'End of life, replaced with new model',
    createdAt: new Date('2022-01-01').toISOString(),
    updatedAt: new Date('2024-10-01').toISOString(),
  },
];

export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    plateNumber: 'ABC-1234',
    make: 'Toyota',
    model: 'Fortuner',
    year: 2023,
    type: 'suv',
    status: 'assigned',
    assignedTo: 'user-agent-1',
    assignedDate: new Date('2024-01-10').toISOString(),
    mileage: 15000,
    lastServiceDate: new Date('2024-10-01').toISOString(),
    nextServiceDate: new Date('2025-01-01').toISOString(),
    fuelType: 'diesel',
    condition: 'excellent',
    notes: 'Primary vehicle for property viewings',
    createdAt: new Date('2023-12-01').toISOString(),
    updatedAt: new Date('2024-01-10').toISOString(),
  },
  {
    id: 'veh-2',
    plateNumber: 'XYZ-5678',
    make: 'Honda',
    model: 'Civic',
    year: 2022,
    type: 'sedan',
    status: 'available',
    mileage: 25000,
    lastServiceDate: new Date('2024-09-15').toISOString(),
    nextServiceDate: new Date('2024-12-15').toISOString(),
    fuelType: 'gasoline',
    condition: 'good',
    notes: 'Available for agent use',
    createdAt: new Date('2022-06-01').toISOString(),
    updatedAt: new Date('2024-09-15').toISOString(),
  },
  {
    id: 'veh-3',
    plateNumber: 'DEF-9012',
    make: 'Mitsubishi',
    model: 'L300',
    year: 2021,
    type: 'van',
    status: 'maintenance',
    mileage: 45000,
    lastServiceDate: new Date('2024-11-05').toISOString(),
    nextServiceDate: new Date('2024-11-15').toISOString(),
    fuelType: 'diesel',
    condition: 'fair',
    notes: 'Brake system maintenance',
    createdAt: new Date('2021-03-01').toISOString(),
    updatedAt: new Date('2024-11-05').toISOString(),
  },
  {
    id: 'veh-4',
    plateNumber: 'GHI-3456',
    make: 'Ford',
    model: 'Ranger',
    year: 2024,
    type: 'truck',
    status: 'available',
    mileage: 5000,
    lastServiceDate: new Date('2024-08-01').toISOString(),
    nextServiceDate: new Date('2025-02-01').toISOString(),
    fuelType: 'diesel',
    condition: 'excellent',
    notes: 'New vehicle for logistics',
    createdAt: new Date('2024-06-01').toISOString(),
    updatedAt: new Date('2024-06-01').toISOString(),
  },
];
